Decompile pppMove and pppPoint
ethteck/kh1 pull request #15
Opened 2023-11-14 00:55 UTC by Xeeynamo

Depends on #7. I will rebase this once #7 is merged.

2023-11-14 02:15 UTC, Yotona commented on symbol_addrs.txt
> +ppvUserStopPartF             = 0x0061095C; // type:s32
I feel like it these should be with the rest of libppp's addrs following line 21

2023-11-14 02:16 UTC, Yotona commented on include/pppfunc.h
> +    /* 0x94 */ struct pppSVECTOR * lpnorm;
pppSVECTOR hasn't been defined yet

2023-11-15 02:13 UTC, ethteck commented on symbol_addrs.txt
> +ppvUserStopPartF             = 0x0061095C; // type:s32
I think keeping it by offset is ideal personally

2023-11-16 02:34 UTC, ethteck requested changes
Left some naming comments - also I prefer left-aligned pointers...I really should set up the CI and format script. I'll try to do it soon, but I've never created a format script so it might take some time for me to figure out the right way to handle it

2023-11-16 02:34 UTC, ethteck commented on include/ppp.h
> +    /* 0x00 */ u8 unk[0xB0];
I prefer unk_00 (And to have underscores in general after unk)

2023-11-16 02:34 UTC, ethteck commented on include/pppfunc.h
> +    short x, y, z;
s16

2023-11-16 02:34 UTC, ethteck commented on include/pppfunc.h
> +    float x, y, z;
f32

2023-11-16 02:34 UTC, ethteck commented on src/ppp/pppMove.c
> +    float val = 0.0f;
f32

2023-11-20 08:54 UTC, merged