Initial Support for new game version: Final Mix
ethteck/kh1 pull request #59
Opened 2024-09-03 06:00 UTC by Yotona

2024-09-03 09:17 UTC, ethteck requested changes
looks good! some minor change requests

2024-09-03 09:17 UTC, ethteck commented on configure.py
> +        "-r",
I'd prefer we call the flag and internal variable version rather than region, since I think there will be different versions for each region

2024-09-03 09:17 UTC, ethteck commented on README.md
> +| Final Mix         | `SLPS_251.98` |`e70bda789916142aafb53d85cef2e806b35ad8d8`|
is this Final Mix (Japan) or is there only one final mix release?

2024-09-03 09:17 UTC, ethteck commented on README.md
> +# Kingdom Hearts De:Compiled
lol I love this

2024-09-03 09:17 UTC, ethteck commented on README.md
> +The game's assets are not included in this repository, and are not required to build the project. They may optionally be extracted by running `./tools/iso/extract.py` on the game's ISO (JP only for n
I think I'd prefer the wording "are not used in this project" since I don't want to give any impression that this allows building the actual game without needing assets.

2024-09-03 19:50 UTC, Yotona commented on README.md
> +| Final Mix         | `SLPS_251.98` |`e70bda789916142aafb53d85cef2e806b35ad8d8`|
For PS2 the only Final Mix release was in Japanese which was more closely based on the US than the original  Japanese. Future consoles were based off this Japanese Final Mix and available in other languages though.

2024-09-03 19:59 UTC, Yotona commented on configure.py
> +        "-r",
The only region with a different version is Japan, which could be the base edition or Final Mix, unless there's minor differences for Greatest Hits they were might support, though I agree FM isn't a "region" and "version" is more universal

2024-09-04 12:57 UTC, ethteck commented on README.md
> +| Final Mix         | `SLPS_251.98` |`e70bda789916142aafb53d85cef2e806b35ad8d8`|
i sheep. thanks

2024-09-04 12:58 UTC, merged